# Taps
tap "oven-sh/bun"

# CLI Tools
brew "awscli"
brew "abyss/tools/awsp"
brew "bat"
brew "oven-sh/bun/bun"
brew "direnv"
brew "docker"
brew "dockutil"
brew "defaultbrowser"
brew "fish"
brew "fnm"
brew "git" # Easier to update git with homebrew
brew "gh"
# Kubernetes tools handled by witco-cli
# brew "kubectl"
# brew "k9s"
# brew "kubectx"
brew "make"
brew "htop"
brew "jq"
brew "lazygit"
brew "lf"
brew "tokei"
brew "vault-cli"
brew "wget"
brew "zoxide"

# Casks (GUI Applications)
cask "helium"
cask "orbstack"
cask "visual-studio-code"

### Post ./mac/install

## Check that these are applied correctly
# Dark mode
# Automatically hide dock
# Remove everything from dock
# Default browser to chrome
# Faster dock response
# Screenshot defaults to jpeg

# Install ghostty
# Add fingerprint
# Install pnpm manually `curl -fsSL https://get.pnpm.io/install.sh | sh -`
# Add bluetooth mouse, adjust sensitivity, and turn natural scrolling off

# brew tap witco/witco https://github.com/witco-oss/homebrew-witco.git
# brew install witco-cli
# witctl config generate
# witctl aws auth login
# witctl completions



### TODO

# Add github pat to shells for vault cli or command to grab github pat
# Set up .env secrets
# Claude setup
