# Navigation
alias c="clear"
alias la="ls -A"
alias ll="ls -l"
alias lr="ls -R"
alias cat="bat"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias f="fish"
alias home="cd ~/code/home"

# Git aliases
alias g="git"
alias ga="git add"
alias gaa="git add -A"
alias gap="git add -p"
alias gf="git commit --fixup"
alias gaf="git add -A; git commit --fixup"
alias gfh="git commit --fixup HEAD"
alias gafh="git add -A; git commit --fixup HEAD"
alias gc="git commit -m"
alias gac="git add -A; git commit -m"
alias gd="git checkout -- ."
alias gdiff="git diff"
alias gdiffs="git diff --staged"
alias gr="git reset HEAD^"
alias gl="git log --oneline --ancestry-path origin/main^..HEAD"
alias gcp="git cherry-pick"
alias main="git checkout main"
alias pull="git pull --rebase origin"
alias push="git push origin"
alias fpush="git push origin --force-with-lease"
alias fetch="git fetch origin"
alias gs="git stash push -u"
alias gsm="git stash push -u -m"
alias gsd="git stash drop"
alias gsl="git stash list"
alias gsp="git stash pop"
alias b="git branch"
alias db="git branch -D"
alias nb="git checkout -b"
alias sb="git checkout"
alias fe="git fetch origin main"
alias re="git rebase origin/main"
alias rei="git rebase -i origin/main"
alias pr="gh pr create -t"
alias prd="gh pr create --draft -t"

# Vault
alias vault-login='vault login -method=github -path=github/cincpro token=$GITHUB_TOKEN'

# Development
alias p="pnpm"
alias docker-clean="docker system prune -a"
