# name: CI

# on:
#   push:
#     branches: main
#   pull_request:

# jobs:
#   nix-matrix:
#     runs-on: ubuntu-latest
#     outputs:
#       matrix: ${{ steps.set-matrix.outputs.matrix }}
#     steps:
#       - uses: actions/checkout@v4
#       - uses: cachix/install-nix-action@v26
#       - id: set-matrix
#         name: Generate Nix Matrix
#         run: |
#           set -Eeu
#           matrix="$(nix eval --accept-flake-config --json './home#githubActions.githubActions.matrix')"
#           echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
#   check:
#     needs: nix-matrix
#     strategy:
#       matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
#     runs-on: ${{ matrix.os }}
#     continue-on-error: true
#     steps:
#       - uses: actions/checkout@v4
#       - uses: cachix/install-nix-action@v26
#       - uses: cachix/cachix-action@v14
#         with:
#           name: freckle
#           authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
#       - name: Check
#         run: nix build --accept-flake-config --print-build-logs --keep-going "./main#${{ matrix.attr }}"
