name: Update flake inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 0'

defaults:
  run:
    working-directory: .

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Update
        run: nix flake update

      - uses: peter-evans/create-pull-request@v6
        with:
          branch: gh/update
          title: Update flake inputs
          body: |
            Automatic run of `nix flake update`.
